version: "3.7"
services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MDATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${MPASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - mongo_vol:/data/db
      - ./mongo_init.sh:/docker-entrypoint-initdb.d/mongo_init.sh
      - ./data.csv:/tmp/data.csv
      - ./data2.csv:/tmp/data2.csv

  mongo-express:
    image: mongo-express
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MPASSWORD}
    depends_on:
      - mongo
    logging:
      driver: none

volumes:
  mongo_vol:
